import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            width: '100%',
            backgroundColor: 'lightblue',
            padding: '1rem',
            display: 'flex',
            justifyContent: 'space-between',
          }}
        >
          <div>
            <Link href="/">Home</Link> {''}
            <Link href={{ pathname: '/animals' }}>Animals</Link> {''}
            <Link
              href={{
                pathname: '/animals/admin',
              }}
            >
              Animal admin
            </Link>
          </div>
          <span>freddy</span>
          {true ? (
            <Link
              href={{
                pathname: '/logout',
              }}
            >
              Logout
            </Link>
          ) : (
            <Link href={{ pathname: '/login' }}>Login</Link>
          )}
        </nav>
        {children}

        <br />
        <hr />
        <br />
        <footer>copyright animals4everyone 2023</footer>
      </body>
    </html>
  );
}
