import { gql } from '@apollo/client';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getClient } from '../util/apolloClient';
import { ApolloClientProvider } from './ApolloClientProvider';
import { LogoutButton } from './LogoutButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const fakeSessionToken = cookies().get('fakeSession');

  const { data } = await getClient().query({
    query: gql`
      query LoggedInAnimal($firstName: String!) {
        loggedInAnimalByFirstName(firstName: $firstName) {
          id
          firstName
          type
          accessory
        }
      }
    `,
    variables: {
      firstName: fakeSessionToken?.value || '',
    },
  });
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            width: '100%',
            backgroundColor: 'lightblue',
            padding: '1rem',
            display: 'flex',
            justifyContent: 'space-between',
          }}
        >
          <div>
            <Link href="/">Home</Link>
            <Link href="/animals">Animals</Link>
            <Link href="/animals/admin">Animal admin</Link>
          </div>
          <span>{data.loggedInAnimalByFirstName?.firstName}</span>
          {data.loggedInAnimalByFirstName?.firstName ? (
            <LogoutButton />
          ) : (
            <Link href="/login">Login</Link>
          )}
        </nav>
        <ApolloClientProvider>{children}</ApolloClientProvider>

        <br />
        <hr />
        <br />
        <footer>copyright animals4everyone 2023</footer>
      </body>
    </html>
  );
}
